### ISSUE TITLE
Possible incompatibility with Node 7.7.2?

### ISSUE THREAD

**Issue by bard** [othiym23/async-listener#102]
Not 100% sure whether to report this on [node-redis](https://github.com/NodeRedis/node_redis), [pm2](https://github.com/Unitech/pm2) or asynclistener.

The following call within node-redis succeeds in Node 7.6.0:

(node_modules/redis/index.js:251)[https://github.com/NodeRedis/node_redis/blob/master/index.js#L251]
```
this.stream = net.createConnection(this.connection_options);
```

In Node 7.7.2, it fails with this stacktrace involving async-listener (imported by pm2):

```
TypeError: "listener" argument must be a function
    at Socket.once (events.js:307:11)
    at Socket.connect (net.js:943:10)
    at Socket.connect (/usr/local/lib/node_modules/pm2/node_modules/async-listener/index.js:76:27)
    at RedisClient.create_stream (/home/bard/Documents/myapp/api/node_modules/redis/index.js:251:31)
    at new RedisClient (/home/bard/Documents/myapp/api/node_modules/redis/index.js:159:10)
    at Object.exports.createClient (/home/bard/Documents/myapp/api/node_modules/redis/index.js:1084:12)
    at new RedisStore (/home/bard/Documents/myapp/api/node_modules/connect-redis/lib/connect-redis.js:77:27)
    at Object.<anonymous> (/home/bard/Documents/myapp/api/app.js:142:28)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:53:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

Sorry for not providing a minimal test case, pressed for time so I just worked around by switching to ioredis, but thought I'd drop this here for reference.

**Comment by bard** [comment]
Sorry for the noise—everything seems to be back to normal with node 7.7.3.
