### ISSUE TITLE
TypeError: Cannot read property 'onread' of null

### ISSUE THREAD

**Issue by paulbjensen** [othiym23/async-listener#13]
Hi,

I'm encountering this error when running the newrelic plugin (1.3.0) on our app. Here is the stacktrace:

```
TypeError: Cannot read property 'onread' of null
    at Server.<anonymous> (/Users/paulbjensen/Work/axisto/sc-live/axisto-live/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/index.js:65:58)
    at Server.EventEmitter.emit (events.js:117:20)
    at TCP.onconnection (net.js:1180:8)
    at TCP.onconnection (/Users/paulbjensen/Work/axisto/sc-live/axisto-live/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:177:31)
```

The app runs on Node 0.10.24 on Mac OS X (Mavericks). I'm running the app with clustering, like this:

``` javascript
'use strict';



require('newrelic');



// Dependencies and configuration
//
var sticky  = require('sticky-session'),
    port    = require('./config').port;



// Boot the application with clustering enabled
//
sticky(function() {
  var app = require('./app');
  app.boot();
  return app;

}).listen(port, function() {
  console.log('\r\n\x1b[36mApplication instance started on port:\x1b[0m '+port);
});



// Handle uncaught exceptions. Bad, sorry.
//
process.on('uncaughtException', function(err){
  console.error('Exception caught:', err);
  console.error(err.stack);
});
```

I will try and provide an application to replicate this, once I've debugged our client's issues. Let me know if there's anything else I can provide.

**Comment by paulbjensen** [comment]
Closing as this is an old issue.
